server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/teamme
    username: app
    password: zetka
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

app:
  jwt:
    secret: "CHANGE_ME_SUPER_SECRET_32_CHARS_MINIMUM_123456"
    issuer: "teamme"
    accessTokenMinutes: 120

cors:
  allowedOrigins: "http://localhost:5173,http://localhost:3000"